services:
  lb:
    image: caddy:2
    volumes:
      - ./load-balancer/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:80"
    networks:
      - web-net
    depends_on:
      - web1
      - web2
      - api


  web1:
    image: caddy:2
    volumes:
      - ./web1:/srv
      - ./web1/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web-net

  web2:
    image: caddy:2
    volumes:
      - ./web2:/srv
      - ./web2/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PASSWORD: ${SA_PASSWORD}
    networks:
      - web-net
      - data-net
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    volumes:
      - db-data:/var/opt/mssql
      - ./db/init:/db/init:ro
    networks:
      - data-net
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" -b
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    entrypoint: ["/bin/bash", "/db/init/entrypoint.sh"]

networks:
  web-net:
  data-net:

volumes:
  db-data: